### ISSUE TITLE
Is this plugin used?

### ISSUE THREAD

**Issue by hvoers** [hvoers/Dancer2-Plugin-Passphrase#7]
I don't use it any more.
Who wants to take over?

**Comment by SysPete** [comment]
@hvoers although I don't use it right now I will be using it as soon as we start migrating Interchange6 from D1 to D2 so I would be happy to take it over.

**Comment by hvoers** [comment]
On Mon, 28 Dec 2015, Peter Mottram wrote:

> @hvoers although I don't use it right now I will be using it as soon as we start migrating Interchange6 from D1 to D2 so I would be happy to take it over.

I wanted to use it in an other plugin but D2 does not allow that.
So, yes please, take it over.

**Comment by SysPete** [comment]
On 28/12/15 17:16, Henk van Oers wrote:
>
> On Mon, 28 Dec 2015, Peter Mottram wrote:
>
> > @hvoers although I don't use it right now I will be using it as soon
> as we start migrating Interchange6 from D1 to D2 so I would be happy
> to take it over.
>
> I wanted to use it in an other plugin but D2 does not allow that.
> So, yes please, take it over.

This *will* be possible once the new Plugin code is released. @xsawyerx
has been busy trying to get it into shape over the last few weeks and
now I'm working on trying to find issues with plugins with failing tests
against new D2 plugin code.

See https://github.com/PerlDancer/Dancer2/pull/1010 for history of
Plugin2 and https://github.com/PerlDancer/Dancer2/issues/1078 where we
are tracking plugins that don't work with new code.

**Comment by xsawyerx** [comment]
@hvoers It *is* possible with the new system. The reason @SysPete contacted you is because we worked on getting all the old plugins to not break under the new system, and he's updating modules left and right to have them keep working on the new system.

It took some time, but we got a good plugin system ready.

**Comment by xsawyerx** [comment]
@SysPete I rewrote a fair chunk of this plugin, I would be happy to lend a hand wherever you need.

**Comment by hvoers** [comment]
New version is on its way to CPAN.

**Comment by hvoers** [comment]
@SysPete  Interchange6 on D2 sounds good.
Send in patches.
Or take over.
What ever.

**Comment by SysPete** [comment]
I'm about to land you with a new PR.

Please beware: this PR can be merged immediately but the resulting plugin should not be released to the CPAN until *after* the next Dancer2 release (or at about the same time).

**Comment by SysPete** [comment]
@hvoers if you'd like me to handle the next CPAN release please add me as co-maint.

**Comment by hvoers** [comment]
@SysPete You now can push to this repo and you have a PAUSE co-maint.

**Comment by SysPete** [comment]
Closing this issue since I have co-maint and plugin2 version is released so all items are covered.

**Comment by hvoers** [comment]
Thank you Peter.
And also thank you for creating Provider::IMAP
It was on my todo-list, but you beat me to it :+1:
